version: "3.0"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: materi-simple-golang-api
    container_name: materi-simple-golang-api
    networks:
        - materisimplegolang
    ports:
        - 4023:4023
networks:
  sidig:
    driver: bridge
    